/**
 * Hoo configuration types
 * Generated by hoo CLI - do not edit manually
 */

export interface PackageInfo {
  /** Package name (from package.json) */
  name: string
  /** Relative path to the package directory */
  path: string
  /** Whether the package is private (not published to npm) */
  private?: boolean
}

export interface WorkerInfo {
  /** Worker name (typically the directory name) */
  name: string
  /** Relative path to the worker directory */
  path: string
}

export interface ImageInfo {
  /** Image logical name */
  name: string
  /** Full image name (e.g., ghcr.io/org/app) */
  image: string
  /** Build context path */
  context?: string
  /** Dockerfile path */
  dockerfile?: string
  /** Tag aliases (e.g., { stable: "latest" }) */
  tags?: Record<string, string>
}

export type SpellcheckFormat = "pretty" | "compact" | "json"

export interface SpellcheckConfig {
  /** Enable/disable spellcheck */
  enabled?: boolean
  /** AI gateway base URL */
  gatewayUrl?: string
  /** Optional path to the system prompt */
  systemPromptPath?: string
  /** Model identifier for the AI gateway */
  model?: string
  /** Language locale (e.g., "en-US") */
  language?: string
  /** Include globs relative to repo root */
  include?: string[]
  /** Exclude globs relative to repo root */
  exclude?: string[]
  /** Allowlisted words */
  allowlist?: string[]
  /** Allowlist file path */
  allowlistFile?: string
  /** Minimum confidence to report (0-1) */
  minConfidence?: number
  /** Max tokens per chunk */
  maxChunkTokens?: number
  /** Max files to scan */
  maxFiles?: number
  /** Max chunks to scan */
  maxChunks?: number
  /** Request timeout in milliseconds */
  timeoutMs?: number
  /** Request concurrency */
  concurrency?: number
  /** Cache results between runs */
  cache?: boolean
  /** Output format */
  format?: SpellcheckFormat
}

export interface HooPlugins {
  /** Spellcheck settings */
  spellcheck?: SpellcheckConfig
  /** Additional plugin configs */
  [key: string]: unknown
}

/** Context passed to additionFilename hook */
export interface AdditionFilenameContext {
  /** Target name (e.g., "@org/core") */
  target: string
  /** Target type */
  targetType: "package" | "worker" | "image"
  /** Bump type */
  bumpType: "major" | "minor" | "patch"
  /** Summary text */
  summary: string
  /** Timestamp string (e.g., "20260126123456789") */
  timestamp: string
}

/** Hook function that generates addition filename (without .md extension) */
export type AdditionFilenameHook = (
  ctx: AdditionFilenameContext
) => string | Promise<string>

/** Available hooks */
export interface HooHooks {
  /** Custom filename generator for addition files */
  additionFilename?: AdditionFilenameHook
}

export interface HooConfig {
  /** Packages in the monorepo */
  packages?: PackageInfo[]
  /** Cloudflare Workers in the monorepo */
  workers?: WorkerInfo[]
  /** Container images */
  images?: ImageInfo[]
  /** Spellcheck settings */
  spellcheck?: SpellcheckConfig
  /** Plugin settings */
  plugins?: HooPlugins
  /** Hooks for customizing behavior */
  hooks?: HooHooks
}

declare const config: HooConfig
export default config
